PATHS:
  base_dir: "E:/Course Materials"

VARS:
  valid_semesters: []
  format: ["L", "T", "P", "C"]
  semesters: ["I", "II", "III", "IV", "V", "VI", "VII", "VIII"]
  url: "https://www.iitg.ac.in/acad/CourseStructure/Btech2018/"